{
  "entities" : [
    {
      "CANDIDATE" : {
        "column" : "Candidate Name",
        "phone" : "Candidate Phone"
      },
      "PANELIST" : {
        "column" : "Domain Interviewer Name"
      }
    }
  ],
  "relations" : [
    {
      "INTERVIEWED_BY" : {
        "from": "Candidate Name",
        "to": "Domain Interviewer Name",
        "properties": {
          "sourcetype" : "Source Type"
        }
      }
    }
  ]
}
